[package]
name = "ckb-hash"
version = "0.112.0-pre"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2021"
description = "CKB default hash function."
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[features]
default = ["blake2b-wasm", "blake2b-native"]
ckb-contract = ["blake2b-wasm"] # This feature is used for CKB contract development

[dependencies]
blake2b-wasm = { package="blake2b-ref", version = "0.3", optional = true}

[target.'cfg(target_arch = "wasm32")'.dependencies]
blake2b-wasm = { package="blake2b-ref", version = "0.3", optional = true}


[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
blake2b-native = {package="blake2b-rs", version = "0.2", optional = true}
