[package]
name = "ckb-migrate"
version = "0.113.0-pre"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2021"
description = "TODO(doc): @quake crate description"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-migration-template = { path = "migration-template", version = "= 0.113.0-pre" }
ckb-db = { path = "../../db", version = "= 0.113.0-pre" }
ckb-logger = { path = "../logger", version = "= 0.113.0-pre" }
ckb-error = { path = "../../error", version = "= 0.113.0-pre" }
ckb-db-schema = { path = "../../db-schema", version = "= 0.113.0-pre" }
ckb-db-migration = { path = "../../db-migration", version = "= 0.113.0-pre" }
ckb-app-config = { path = "../app-config", version = "= 0.113.0-pre" }
ckb-types = { path = "../types", version = "= 0.113.0-pre" }
ckb-store = { path = "../../store", version = "= 0.113.0-pre" }
ckb-chain-spec = { path = "../../spec", version = "= 0.113.0-pre" }
indicatif = "0.16"
console = ">=0.9.1, <1.0.0"
ckb-hash = { path = "../hash", version = "= 0.113.0-pre" }
num_cpus = "1.10"

[dev-dependencies]
ckb-systemtime = {path = "../systemtime", version = "= 0.113.0-pre", features = ["enable_faketime"]  }
