name: Package

permissions:
  # for actions/create-release, actions/upload-release-asset
  contents: write

concurrency:
  group: package-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "pkg/*"

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  CKB_CLI_VERSION: v1.11.0

jobs:
  package-for-mac:
    name: package-for-mac
    runs-on: macos-12
    strategy:
      matrix:
        include:
          - rel_pkg: "x86_64-apple-darwin.zip"
            build_target: "prod"
          - rel_pkg: "x86_64-apple-darwin-portable.zip"
            build_target: "prod_portable"
    steps:
      - uses: actions/checkout@v3
        with:
          ref: v0.117.0
          fetch-depth: 5
      - name: Set Env
        run: |
          export GIT_TAG_NAME=v0.117.0
          echo "GIT_TAG_NAME=$GIT_TAG_NAME" >> $GITHUB_ENV
      - name: Build CKB and Package CKB
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
          GPG_SIGNER: ${{ secrets.GPG_SIGNER }}
        run: |
          export GIT_TAG_NAME=v0.117.0

          make ${{ matrix.build_target }}

          gpg --quiet --batch --yes --decrypt --passphrase="$LARGE_SECRET_PASSPHRASE" --output devtools/ci/signer.asc devtools/ci/signer.asc.gpg
          gpg --import devtools/ci/signer.asc
          devtools/ci/package.sh target/prod/ckb
          mv ${{ github.workspace }}/releases/ckb_${{env.GIT_TAG_NAME }}_${{env.REL_PKG }} ${{ github.workspace }}
          mv ${{ github.workspace }}/releases/ckb_${{env.GIT_TAG_NAME }}_${{env.REL_PKG }}.asc ${{ github.workspace }}
      - name: upload-zip-file
        uses: actions/upload-artifact@v2
        with:
          name: ckb_${{env.GIT_TAG_NAME }}_${{env.REL_PKG }}
          path: ckb_${{env.GIT_TAG_NAME }}_${{env.REL_PKG }}
      - name: upload-asc-file
        uses: actions/upload-artifact@v2
        with:
          name: ckb_${{env.GIT_TAG_NAME }}_${{env.REL_PKG }}.asc
          path: ckb_${{env.GIT_TAG_NAME }}_${{env.REL_PKG }}.asc
    env:
      REL_PKG: ${{ matrix.rel_pkg }}
